### PR TITLE
Update dependencies in build hook (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
ah, good.

**Comment by alanking** [comment]
Perhaps https://github.com/irods/irods/issues/7247 and/or https://github.com/irods/externals/issues/162 for the issue(s)

**Comment by trel** [comment]
or just release activities for 4.3.1 (irods/irods#6412)

**Comment by korydraughn** [comment]
#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
