### PR TITLE
[#26] Detect and use proper libcurl package dependency for debian/ubuntu (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #26 for master

While we do build against `libcurl-gnutls` in the development repository, it is theoretically possible to build against the `nss` and `openssl` flavors of `libcurl` as well. I've implemented logic to detect which version cmake picks up and apply the appropriate package dependency.

### CODE REVIEW

**Comment by trel** [comment]
does this change our package recommendation/requirements/instructions for installing?   i think it does not...

**Comment by SwooshyCueb** [comment]
Didn't get a notification for this comment for some reason.

I wouldn't imagine we would need to change our recommendations there, as the package manager should pull in everything automatically.

**Comment by trel** [comment]
very good - let's # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
